sudo: required
services:
    - docker

before-install:
    - docker build -t devopsothman/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true devopsothman/docker-react npm run test -- --coverage


deploy:
    provider: elastickbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-752647321510"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY