sudo: required
services:
    - docker

before-install:
    - docker build -t devopsothman/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true devopsothman/docker-react npm run test -- --coverage   